# snapshot (optionnal)
# nettype (default:force)
# proxy (optional)
# TZ (optional)
# genesisfile (optional)
# proofparameters:  (default:/var/tmp/filecoin-proof-parameters/)

version: '3'
services:
  genesis:
    image: tanlang/forcenet:nv19
    environment:
      - TZ=${TZ-UTC}
    volumes:
      - ${proofparameters-/var/tmp/filecoin-proof-parameters/}:/var/tmp/filecoin-proof-parameters/
      - ./.venus/env:/env
      - ./.venus/root:/root
      - ./compose:/compose
    entrypoint: "/compose/scripts/lotus.sh"

  auth:
    image: filvenus/venus-auth:latest
    environment:
      - TZ=${TZ-UTC}
    volumes:
      - ./.venus/env:/env
      - ./.venus/root:/root
      - ./compose:/compose
    entrypoint: "/compose/scripts/venus-auth.sh"

  node:
    image: filvenus/venus:latest
    volumes:
      - ${proofparameters-/var/tmp/filecoin-proof-parameters/}:/var/tmp/filecoin-proof-parameters/
      - ./.venus/env:/env
      - ./.venus/root:/root
      - ./compose:/compose
    environment:
      - GOLOG_LOG_LEVEL=debug
      - HTTPS_PROXY=${proxy}
      - nettype=${nettype-force}
      - TZ=${TZ-UTC}
      - snapshot=${snapshot}
      - genesisfile=${genesisfile}
    entrypoint: "/script/wait-for-it.sh auth:8989 -t 0  --  /compose/scripts/venus.sh"
    depends_on:
      - auth

  gateway:
    image: filvenus/venus-gateway:latest
    environment:
      - TZ=${TZ-UTC}
    volumes:
      - ./.venus/env:/env
      - ./.venus/root:/root
      - ./compose:/compose

    entrypoint: "/script/wait-for-it.sh auth:8989 -t 0  --  /compose/scripts/venus-gateway.sh"
    depends_on:
      - auth

  messager:
    image: filvenus/venus-messager:latest
    volumes:
      - ./.venus/env:/env
      - ./.venus/root:/root
      - ./compose:/compose
    environment:
      - TZ=${TZ-UTC}
    entrypoint: "/script/wait-for-it.sh node:3453 -t 0  -- /compose/scripts/venus-messager.sh"
    depends_on:
      - auth
      - gateway

  miner:
    image: filvenus/venus-miner:latest
    volumes:
      - ./.venus/env:/env
      - ./.venus/root:/root
      - ./compose:/compose
    environment:
      - nettype=${nettype-butterfly}
      - TZ=${TZ-UTC}
    entrypoint: "/script/wait-for-it.sh node:3453 -t 0  -- /compose/scripts/venus-miner.sh"
    depends_on:
      - auth
      - gateway

  market:
    image: filvenus/venus-market:latest
    environment:
      - TZ=${TZ-UTC}
    volumes:
      - ./.venus/env:/env
      - ./.venus/root:/root
      - ./compose:/compose

    entrypoint: "/script/wait-for-it.sh messager:39812 -t 0  -- /compose/scripts/venus-market.sh"
    depends_on:
      - auth
      - node
      - gateway

  wallet:
    image: filvenus/venus-wallet:latest
    environment:
      - TZ=${TZ-UTC}
      - nettype=${nettype-butterfly}
    volumes:
      - ./.venus/env:/env
      - ./.venus/root:/root
      - ./compose:/compose
    depends_on:
      - auth
      - gateway
    entrypoint: "/script/wait-for-it.sh node:3453 -t 0  -- /compose/scripts/venus-wallet.sh"

  vsm:
    image: filvenus/venus-sector-manager:latest
    environment:
      - TZ=${TZ-UTC}
    volumes:
      - ${proofparameters-/var/tmp/filecoin-proof-parameters/}:/var/tmp/filecoin-proof-parameters/
      - ./.venus/env:/env
      - ./.venus/root:/root
      - ./compose:/compose
    entrypoint: "/compose/scripts/wait-for-it.sh market:41235 -t 0  -- /compose/scripts/venus-sector-manager.sh"

  worker:
    image: filvenus/venus-worker:latest
    environment:
      - TZ=${TZ-UTC}
    volumes:
      - ${proofparameters-/var/tmp/filecoin-proof-parameters/}:/var/tmp/filecoin-proof-parameters/
      - ./.venus/env:/env
      - ./.venus/root:/root
      - ./compose:/compose
    entrypoint: "/compose/scripts//wait-for-it.sh vsm:1789 -t 0 -- /compose/scripts/venus-worker.sh"
    depends_on:
      - vsm

  ssm:
    image: filvenus/venus-tool:latest
    environment:
      - TZ=${TZ-UTC}
    volumes:
      - ./.venus/env:/env
      - ./.venus/root:/root
      - ./compose:/compose
    entrypoint: "/script/wait-for-it.sh market:41235 -t 0  -- /compose/scripts/venus-tool.sh"
